version: "3"
services:
  
  app:
  
    build: ./Docker/app/.
    container_name: ${DOCKER_APP_SERVICE_NAME}
    command: ["npm", "run", "dev"]
  
    env_file:
      - .env
    
    environment:
      - SEQUELIZE_HOST=${DOCKER_APP_MYSQL_NAME}
      - SEQUELIZE_DATABASE=${DOCKER_APP_MYSQL_DATABASE}

    volumes:
      - ./src:/app/src
      
    ports:
      - ${DOCKER_APP_PORT}:3000
    
    depends_on:
      - mysql
  
  mysql:
    platform: linux/x86_64
    build: ./Docker/database/.
    restart: always
    container_name: ${DOCKER_APP_MYSQL_NAME}
  
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=${DOCKER_APP_MYSQL_DATABASE}

    ports:
      - ${DOCKER_APP_MYSQL_PORT}:3306
  
    command: 
      - --default-authentication-plugin=mysql_native_password